general {
    hide_cursor = true
    ingore_empty_input = true
    immediate_render = true
}

animations {
    enabled = false
}

background {
    path = screenshot
    blur_passes = 4
}

background {
    color = rgba(0, 0, 0, 0.7)
}

label {
    text = hyprlocked
    color = rgb(255, 255, 255)
    font_family = monospace bold
}

input-field {
    hide_input = true
    size = 230, 120
    rounding = 0
    placeholder_text =
    fail_text =

    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(0, 0, 0, 0)
    hide_input_base_color = rgb(255, 255, 255)
}

