general {
    hide_cursor = true
    ignore_empty_input = true
}

# BACKGROUND
background {
    monitor =
    path = ~/wallpaper.png
    color = rgba(0, 0, 0, 0.8)
    blur_passes = 4
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgb(255, 255, 255)
    font_size = 75
    font_family = JetBrains Mono Extrabold
    position = 0, 150
    halign = center
    valign = center
}

# TITLE
label {
    monitor =
    text = $USER
    text_align = center
    color = rgb(255, 255, 255)
    font_size = 26
    font_family = Monospace
    position = 0, 70
    halign = center
    valign = center
}

# INPUT
input-field {
    monitor =
    halign = center
    valign = center
    size = 230, 45

    font_family = JetBrains Mono Bold
    font_color = rgb(255, 255, 255)
    placeholder_text =

    outline_thickness = 0
    outer_color = rgba(0, 0, 0, 0.5)
    inner_color = rgba(0, 0, 0, 0)

    fail_text = $FAIL
}
