general {
    hide_cursor = true
    ignore_empty_input = true
}

# BACKGROUND
background {
    monitor =
    path =
    color = rgba(0, 0, 0, 0.8)
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo "$TIME"
  color = rgb(255, 255, 255)
  font_size = 95
  font_family = JetBrains Mono Extrabold
  position = 0, 200
  halign = center
  valign = center
}

# TITLE
label {
    monitor =
    text = hyprlocked
    text_align = center
    color = rgb(255, 255, 255)
    font_size = 36
    font_family = Monospace
    position = 0, 100
    halign = center
    valign = center
}

# INPUT
input-field {
   monitor =
   halign = center
   valign = center
   size = 230, 45
   outline_thickness = 2
   outer_color = rgba(0, 0, 0, 0)
   inner_color = rgba(0, 0, 0, 0)
   font_color = rgb(255, 255, 255)
   placeholder_text =
   fail_text = $FAIL
}
